language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dpardo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dpardo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "docker"
  bucket-name: "elasticbeanstalk-us-east-2-655615749373"
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
