FROM node:alpine
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
#RUN chown -R 777 /home/node/app/node_modules
CMD ["npm", "run", "start"]

